---
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: 17
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'

verifier:
  name: inspec

platforms:
  - name: rockylinux-8
    driver_plugin: docker
    driver:
      image: rockylinux:8
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: centos-7
    driver_plugin: docker
    driver:
      image: centos:7
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'

suites:
  - name: default
    run_list:
      - recipe[test-clickhouse::install_zookeeper]
      - recipe[test-clickhouse::test_clickhouse_server]
      - recipe[test-clickhouse::test_zookeeper_config]
      - recipe[test-clickhouse::test_macros_config]
      - recipe[test-clickhouse::test_remote_servers_config]
      - recipe[test-clickhouse::test_custom_config]
      - recipe[test-clickhouse::test_compression_config]
      - role[throughout_config_xml]
